### ISSUE TITLE
Nombre de atributo de tabla principal inválido para módulo de servicios

### ISSUE THREAD

**Issue by davideluque** [davideluque/sigulab2#3]
El cambio de nombre de un atributo de la tabla espacios_fisicos en modelos_base.py afecta al módulo de servicios causando un bug en todo el funcionamiento del módulo.

**Comportamiento esperado:** funcionamiento normal del módulo de servicios. Es posible añadir, eliminar servicios, visualizar ficha de servicios, solicitar, entre otros.

**Comportamiento actual:** no es posible añadir, editar servicios, visualizar fichas, solicitar servicios, etc.

**Código que causa el error:**
db.define_table(
    'espacios_fisicos',
    #Atributos;
    **Field('nombre', 'string', unique=True, notnull=True, label=T('Nombre')),**
    Field('uso', 'string', notnull=True, label=T('Uso del espacio físico')),
    #Referencia (Revisar si el label es asistio o organizo)
    Field('dependencia', 'reference dependencias',
          requires=IS_IN_DB(db, db.dependencias.id, '%(nombre)s', zero=None), label=T('Dependencia'))
    , migrate=False)

**Solución propuesta:** regresar a la definición previa de la tabla.
db.define_table(
    'espacios_fisicos',
    #Atributos;
    **Field('codigo', 'string', unique=True, notnull=True, label=T('Código del espacio físico')),**
    Field('uso', 'string', notnull=True, label=T('Uso del espacio físico')),
    #Referencia (Revisar si el label es asistio o organizo)
    Field('dependencia', 'reference dependencias',
          requires=IS_IN_DB(db, db.dependencias.id, '%(nombre)s', zero=None), label=T('Dependencia'))
    , migrate=False)

**Comment by german1608** [comment]
Esto esta resuelto en el repo de samuel.
